#sudo docker-compose -f docker/common/docker-compose.yml up
version: '2'
services:
    eurekaserver:		#每个正在启动的服务都会有一个标签.这个标签将成为Docker实例启动时的DNS条目，其他服务将通过这个DNS条目访问这个服务
         image:
             cjy/tmx-eurekasvr:cjy
         ports:
             - "8761:8761"	#对外暴露的端口

    configserver:
        image:
            cjy/tmx-confsvr:cjy
        ports:
            - "8888:8888"
        environment:
            EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
            EUREKASERVER_PORT: "8761"

    zipkin:
        image: cjy/tmx-zipkinsvr:cjy
        ports:
            - "9411:9411"
        environment:
            SERVER_PORT: "9411"

            #    zuulserver:
            #        image: cjy/tmx-zuulsvr:cjy
            #        ports:
            #            - "5555:5555"
            #        environment:
            #            PROFILE: "default"
            #            SERVER_PORT: "5555"
            #            CONFIGSERVER_URI: "http://configserver:8888"
            #            EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
            #            ZIPKIN_URI: "http://zipkin:9411"
            #            DATABASESERVER_PORT: "5432"
            #            EUREKASERVER_PORT:   "8761"
            #            CONFIGSERVER_PORT:   "8888"
            #            ZIPKIN_PORT:         "9411"

    specialroutesservice:
        image: cjy/tmx-specialroutes-service:cjy
        ports:
            - "8002:8002"
        environment:
            PROFILE: "default"
            SERVER_PORT: "8002"
            CONFIGSERVER_URI: "http://configserver:8888"
            EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
            ZIPKIN_URI: "http://zipkin:9411"
            DATABASESERVER_PORT: "3306"
            EUREKASERVER_PORT:   "8761"
            CONFIGSERVER_PORT:   "8888"
            ZUULSERVER_PORT:     "5555"
            ZIPKIN_PORT:         "9411"

    authenticationservice:
        image: cjy/tmx-authentication-service:cjy
        ports:
            - "8003:8003"
        environment:
        environment:
            PROFILE: "default"
            SERVER_PORT: "8003"
            CONFIGSERVER_URI: "http://configserver:8888"
            EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
            DATABASE_PORT: "3306"
            EUREKASERVER_PORT:   "8761"
            CONFIGSERVER_PORT:   "8888"

    licensingservice:
        image: cjy/tmx-licensing-service:cjy
        ports:
            - "8000:8000"
        environment:
            PROFILE: "dev"
            SERVER_PORT: "8000"
            CONFIGSERVER_URI: "http://configserver:8888"
            EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
            ZIPKIN_URI: "http://zipkin:9411"
            KAFKASERVER_URI: "kafkaserver"
            ZKSERVER_URI: "kafkaserver"
            DATABASESERVER_PORT: "3306"
            EUREKASERVER_PORT:   "8761"
            CONFIGSERVER_PORT:   "8888"
            ZUULSERVER_PORT:     "5555"
            KAFKASERVER_PORT:    "2181"
            REDIS_PORT:          "6379"
            ZIPKIN_PORT:         "9411"

    organizationservice:
        image: cjy/tmx-organization-service:cjy
        ports:
        - "8001:8001"
        environment:
            PROFILE: "dev"
            SERVER_PORT: "8001"
            CONFIGSERVER_URI: "http://configserver:8888"
            EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
            ZIPKIN_URI: "http://zipkin:9411"
            KAFKASERVER_URI: "kafkaserver"
            ZKSERVER_URI: "kafkaserver"
            DATABASESERVER_PORT: "3306"
            EUREKASERVER_PORT:   "8761"
            CONFIGSERVER_PORT:   "8888"
            ZUULSERVER_PORT:     "5555"
            KAFKASERVER_PORT:    "2181"
            REDIS_PORT:          "6379"
            ZIPKIN_PORT:         "9411"

