version: '2'
services:
    eurekaserver:
         image:
             cjy/tmx-eurekasvr:cjy
         ports:
             - "8761:8761"

    configserver:
        image:
            cjy/tmx-confsvr:cjy
        ports:
            - "8888:8888"
        environment:
            EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
            EUREKASERVER_PORT: "8761"

    zipkin:
        image: cjy/tmx-zipkinsvr:cjy
        ports:
            - "9411:9411"
        environment:
            SERVER_PORT: "9411"

    zuulserver:
        image: cjy/tmx-zuulsvr:cjy
        ports:
            - "5555:5555"
        environment:
            PROFILE: "default"
            SERVER_PORT: "5555"
            CONFIGSERVER_URI: "http://configserver:8888"
            EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
            ZIPKIN_URI: "http://zipkin:9411"
            DATABASESERVER_PORT: "5432"
            EUREKASERVER_PORT:   "8761"
            CONFIGSERVER_PORT:   "8888"
            ZIPKIN_PORT:         "9411"

    licensingservice:
        image: cjy/tmx-licensing-service:cjy
        ports:
            - "8000:8000"
        environment:
            PROFILE: "dev"
            SERVER_PORT: "8000"
            CONFIGSERVER_URI: "http://configserver:8888"
            EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
            ZIPKIN_URI: "http://zipkin:9411"
            KAFKASERVER_URI: "kafkaserver"
            ZKSERVER_URI: "kafkaserver"
            DATABASESERVER_PORT: "3306"
            EUREKASERVER_PORT:   "8761"
            CONFIGSERVER_PORT:   "8888"
            ZUULSERVER_PORT:     "5555"
            KAFKASERVER_PORT:    "2181"
            REDIS_PORT:          "6379"
            ZIPKIN_PORT:         "9411"

            #organizationservice:
            #    image: cjy/tmx-organization-service:cjy
            #    ports:
            #    - "8001:8001"
            #    environment:
            #        PROFILE: "dev"
            #        SERVER_PORT: "8001"
            #        CONFIGSERVER_URI: "http://configserver:8888"
            #        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
            #        ZIPKIN_URI: "http://zipkin:9411"
            #        KAFKASERVER_URI: "kafkaserver"
            #        ZKSERVER_URI: "kafkaserver"
            #        DATABASESERVER_PORT: "3306"
            #        EUREKASERVER_PORT:   "8761"
            #        CONFIGSERVER_PORT:   "8888"
            #        ZUULSERVER_PORT:     "5555"
            #        KAFKASERVER_PORT:    "2181"
            #        ZIPKIN_PORT:         "9411"
            #        ENCRYPT_KEY:       "IMSYMMETRIC"

    redis:
        image: redis:alpine
        ports:
            - 6379:6379

    kafkaserver:
        image: spotify/kafka
        ports:
            - 2181:2181
            - 9092:9092

    database:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'license'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: '123456@123456'
            # Password for root access
            MYSQL_ROOT_PASSWORD: '123456@123456'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            - my-db:/var/lib/mysql

# Names our volume
volumes:
    my-db:
