eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 5 #在服务器接收请求之前等待的初始时间

  #Setting logging levels
  logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.thoughtmechanix: DEBUG
