#每次服务注册需要30s时间才能显示在Eureka服务中，因为Eureka需要从服务接收3次连续心跳包ping，每次心跳包ping间隔10s，然后才能使用这个服务。在部署
#和测试服务时，要牢记这一点。
#Default port is 8761
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false #不要使用Eureka服务进行注册
    fetchRegistry: false  #不要在本地缓存注册表信息