spring:
  jpa:
    show-sql: true

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/license?serverTimezone=UTC&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root

debug:
  true

logging:
  path: logs/
  level:
    com: debug