zuul:
  prefix:  /api
  routes:
    organizationservice: /organization/**
    baidu:
      path: /it/**
      url: https://www.baidu.com/
    baidu2:
      url: http://www.ityouknow.com/
      path: /it2/**
#超时
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 2
