signing:
  key: "345345fsdfsf5345"

zuul:
  sensitiveHeaders: Cookie,Set-Cookie #这一配置是黑名单,它含Zuul不会传播到下游服务的敏感首部。(Cookie、 Set- Cookie 和 Authorization）
  prefix:  /api
  routes:
    organizationservice: /organization/**
    baidu:
      path: /it/**
      url: https://www.baidu.com/
    baidu2:
      url: http://www.ityouknow.com/
      path: /it2/**
#超时
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 2
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10
