zuul:
  routes:
    #自定义路由
    organizationservice: /organization/**
    #静态路由
    baidu:
      path: /baidu/**
      url: https://www.baidu.com/
    google:
      url: https://www.google.com/
      path: /google/**

eureka:
  instance:
    #true注册服务的IP，而不是服务器名称
    #为什么偏向于IP地址在默认情况下，Eureka在尝试注册服务 ，将会使用主机名让外界与它进行联系。这种方式在基于服务器的环境中运行良好，
    #在这样的环境中，服务 被分配一个DNS支持的主机名。但是，在基于容器的部署（如Docker）中，容器将以随机生成的主机名启动，并且该容器没有DNS记录。
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

debug:
  true

logging:
  path: logs/
  level:
    com: debug
